// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASWyfMIE2PV_jzxdTcpwM0XHrVgU2_kL4',
    appId: '1:617784130089:web:f343b3e67c229bb802ba38',
    messagingSenderId: '617784130089',
    projectId: 'project-mini-9a95a',
    authDomain: 'project-mini-9a95a.firebaseapp.com',
    storageBucket: 'project-mini-9a95a.firebasestorage.app',
    measurementId: 'G-GZCW6VSE88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0nezazDB8HZOL8p5kNr4LDDRXIrZjSnk',
    appId: '1:617784130089:android:21563dac6a09175d02ba38',
    messagingSenderId: '617784130089',
    projectId: 'project-mini-9a95a',
    storageBucket: 'project-mini-9a95a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB7GXJKP8hFoTUsigoU66ISSxPWn9Kf1M',
    appId: '1:617784130089:ios:a1906abe141cb1ec02ba38',
    messagingSenderId: '617784130089',
    projectId: 'project-mini-9a95a',
    storageBucket: 'project-mini-9a95a.firebasestorage.app',
    iosBundleId: 'com.example.projectMini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB7GXJKP8hFoTUsigoU66ISSxPWn9Kf1M',
    appId: '1:617784130089:ios:a1906abe141cb1ec02ba38',
    messagingSenderId: '617784130089',
    projectId: 'project-mini-9a95a',
    storageBucket: 'project-mini-9a95a.firebasestorage.app',
    iosBundleId: 'com.example.projectMini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASWyfMIE2PV_jzxdTcpwM0XHrVgU2_kL4',
    appId: '1:617784130089:web:3920cdfbfab835de02ba38',
    messagingSenderId: '617784130089',
    projectId: 'project-mini-9a95a',
    authDomain: 'project-mini-9a95a.firebaseapp.com',
    storageBucket: 'project-mini-9a95a.firebasestorage.app',
    measurementId: 'G-SY72FH526L',
  );
}
